type User @table {
  displayName: String!
  email: String!
  role: String!
  createdAt: Timestamp!
  photoUrl: String
  phoneNumber: String
  address: String
}

type Event @table {
  title: String!
  startDate: Timestamp!
  endDate: Timestamp!
  location: String!
  description: String!
  createdAt: Timestamp!
  imageUrl: String
  rsvpRequired: Boolean
}

type Announcement @table {
  title: String!
  content: String!
  publishedAt: Timestamp!
  author: User
  expiryDate: Timestamp
}

type Ministry @table {
  name: String!
  description: String!
  createdAt: Timestamp!
  imageUrl: String
  contactPerson: User
}

type RSVP @table {
  status: String!
  createdAt: Timestamp!
  numberOfGuests: Int
  user: User!
  event: Event!
}